# Generated by Django 3.0.5 on 2020-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='bairro',
            field=models.CharField(blank=True, default='Pituba', help_text='Informe o bairro', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='razao_social',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
