# Generated by Django 3.0.5 on 2020-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0003_auto_20200430_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='bairro',
            field=models.CharField(blank=True, default='Pituba', help_text='Informe o bairro', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cidade',
            field=models.CharField(default='Salvador', help_text='Informe a cidade', max_length=50),
        ),
    ]
