# Generated by Django 3.0.5 on 2020-05-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20200430_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(help_text='Informe o código do cliente', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='cliente@cliente.com.br', help_text='Informe o e-mail do cliente', max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Informe o nome do cliente', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(default='(071) 9 9999-9999', help_text='Informe o telefone do cliente', max_length=20),
        ),
    ]
