# Generated by Django 3.0.5 on 2020-05-01 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participantes', '0004_auto_20200430_1241'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='participante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='participantes.Participante'),
            preserve_default=False,
        ),
    ]
