# Generated by Django 3.0.5 on 2020-04-29 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do colaborador', max_length=100)),
                ('telefone', models.CharField(help_text='Informe o número de telefone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email do colaborador', max_length=30, null=True)),
                ('gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborador', to='colaboradores.Colaborador')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
